// 上海金铃橡胶制品有限公司 - 产品数据库

export interface Product {
  id: string;
  slug: string; // SEO-friendly URL slug
  name: string;
  nameEn: string;
  nameAr?: string; // Arabic name
  nameDe?: string; // German name
  nameEs?: string; // Spanish name
  category: string;
  categoryEn: string;
  images: {
    main: string;
    side?: string;
    additional?: string[];
  };
  description: string;
  descriptionEn: string;
  descriptionAr?: string; // Arabic description
  descriptionDe?: string; // German description
  descriptionEs?: string; // Spanish description
  features: string[];
  featuresEn: string[];
  specifications: Record<string, string>;
  specificationsEn?: Record<string, string>; // English specifications
  applications: string[];
  applicationsEn: string[];
  applicationsAr?: string[]; // Arabic applications
  applicationsDe?: string[]; // German applications
  applicationsEs?: string[]; // Spanish applications
  color: string;
  material: string;
}

export const productCategories = [
  { id: 'protective-suits', name: '防护服系列', nameEn: 'Protective Suits' },
  { id: 'rainwear', name: '雨衣系列', nameEn: 'Rainwear Series' },
  { id: 'workwear', name: '工装系列', nameEn: 'Workwear Series' },
];

export const products: Product[] = [
  // ==================== 防护服系列 ====================
  {
    id: '3015',
    slug: 'double-coated-acid-resistant-suit-3015',
    name: '双胶防酸分式工作服',
    nameEn: 'Double-Coated Acid-Resistant Suit',
    nameAr: 'بدلة مقاومة للأحماض مزدوجة الطلاء',
    nameDe: 'Doppelt beschichteter Säureschutzanzug',
    nameEs: 'Traje resistente a ácidos de doble recubrimiento',
    category: 'protective-suits',
    categoryEn: 'Protective Suits',
    images: {
      main: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F3015%E6%AD%A3%E9%9D%A2.jpg&nonce=cf6058aa-4d27-4450-b3cf-fbc6bc3560d7&project_id=7620626575964323874&sign=c6fb5c7be7c98ae3e8896fde79d1dd6ad4bde6fcf663ec969578f01408732700',
      side: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F3015%E4%BE%A7%E9%9D%A2.jpg&nonce=a57f8f6a-82fc-4b33-bbad-68a7431a46d5&project_id=7620626575964323874&sign=998066ca24fe0e54eb309f43b9010b397aec14e47de73c6aa7883cf70b2bb443',
    },
    description: '双胶防酸分式工作服，内料采用尼龙长丝布，涂层为氯丁胶主材，具有防酸碱类化学品溶剂喷溅功能。适合化工、实验室等作业环境。',
    descriptionEn: 'Double-coated acid-resistant suit with nylon filament cloth lining and neoprene coating. Provides protection against acid and alkali chemical splashes. Suitable for chemical and laboratory environments.',
    descriptionAr: 'بدلة مقاومة للأحماض مزدوجة الطلاء مع بطانة من قماش خيوط النايلون وطلاء النيوبرين. توفر حماية ضد رشاش المواد الكيميائية الحمضية والقلوية. مناسبة لبيئات المختبرات والصناعات الكيميائية.',
    descriptionDe: 'Doppelt beschichteter säurebeständiger Anzug mit Nylon-Filamentgewebe-Futter und Neopren-Beschichtung. Bietet Schutz gegen Säure- und Laugenspritzer. Geeignet für chemische und Laborumgebungen.',
    descriptionEs: 'Traje resistente a ácidos de doble recubrimiento con forro de tela de filamento de nailon y recubrimiento de neopreno. Proporciona protección contra salpicaduras de ácidos y álcalis. Adecuado para entornos químicos y de laboratorio.',
    features: [
      '双胶涂层',
      '防酸碱喷溅',
      '尼龙长丝内料',
      '氯丁胶涂层',
      '分体式设计',
    ],
    featuresEn: [
      'Double-coated design',
      'Acid and alkali splash resistant',
      'Nylon filament lining',
      'Neoprene coating',
      'Two-piece design',
    ],
    specifications: {
      '型号': '3015',
      '品名': '双胶防酸分式工作服',
      '内料': '尼龙长丝布',
      '涂层': '氯丁胶主材',
      '功能': '防酸碱类化学品溶剂喷溅',
      '尺码': 'S/M/L/XL/XXL',
      '认证': 'CE/ISO',
    },
    specificationsEn: {
      'Model': '3015',
      'Product Name': 'Double-Coated Acid-Resistant Suit',
      'Lining': 'Nylon Filament Cloth',
      'Coating': 'Neoprene Main Material',
      'Function': 'Acid and Alkali Chemical Splash Protection',
      'Size': 'S/M/L/XL/XXL',
      'Certification': 'CE/ISO',
    },
    applications: ['化工行业', '实验室作业', '酸碱环境', '化学品处理'],
    applicationsEn: ['Chemical industry', 'Laboratory work', 'Acid/alkali environments', 'Chemical handling'],
    applicationsAr: ['الصناعة الكيميائية', 'عمل المختبرات', 'بيئات الأحماض والقلويات', 'التعامل مع المواد الكيميائية'],
    applicationsDe: ['Chemische Industrie', 'Laborarbeit', 'Säure-/Laugenumgebungen', 'Chemikalienhandhabung'],
    applicationsEs: ['Industria química', 'Trabajo de laboratorio', 'Entornos de ácidos/álcalis', 'Manejo de químicos'],
    color: '多色可选',
    material: '尼龙长丝布+氯丁胶',
  },
  {
    id: '3019',
    slug: 'double-coated-acid-resistant-long-suit-3019',
    name: '双胶防酸长式工作服',
    nameEn: 'Double-Coated Acid-Resistant Long Suit',
    nameAr: 'بدلة طويلة مقاومة للأحماض مزدوجة الطلاء',
    nameDe: 'Langer doppelt beschichteter Säureschutzanzug',
    nameEs: 'Traje largo resistente a ácidos de doble recubrimiento',
    category: 'protective-suits',
    categoryEn: 'Protective Suits',
    images: {
      main: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F3019%E6%AD%A3%E9%9D%A2.jpg&nonce=851bc232-5f9b-43fd-b635-f0ba2e48159a&project_id=7620626575964323874&sign=1c96ce09402ab1b7252a0ad17c13ce67aedddf8ea1970e0b5d88b3b5cdd19813',
      side: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F3019%E4%BE%A7%E9%9D%A2.jpg&nonce=861f1c76-f36f-47ae-9754-94b3644093ab&project_id=7620626575964323874&sign=11992935a3341d4be1ca1ac2370bce5ea80cd493aa9edb131e2eee6e1389b5a9',
    },
    description: '双胶防酸长式工作服，内料采用尼龙长丝布，涂层为氯丁胶主材，具有防酸碱类化学品溶剂喷溅功能。适合化工、实验室等作业环境。',
    descriptionEn: 'Double-coated acid-resistant long suit with nylon filament cloth lining and neoprene coating. Provides protection against acid and alkali chemical splashes. Suitable for chemical and laboratory environments.',
    descriptionAr: 'بدلة طويلة مقاومة للأحماض مزدوجة الطلاء مع بطانة من قماش خيوط النايلون وطلاء النيوبرين. توفر حماية ضد رشاش المواد الكيميائية الحمضية والقلوية.',
    descriptionDe: 'Langer doppelt beschichteter säurebeständiger Anzug mit Nylon-Filamentfutter und Neopren-Beschichtung. Bietet Schutz gegen Säure- und Laugenspritzer.',
    descriptionEs: 'Traje largo resistente a ácidos de doble recubrimiento con forro de tela de filamento de nailon y recubrimiento de neopreno. Proporciona protección contra salpicaduras de ácidos y álcalis.',
    features: [
      '双胶涂层',
      '防酸碱喷溅',
      '尼龙长丝内料',
      '氯丁胶涂层',
      '长款设计',
    ],
    featuresEn: [
      'Double-coated design',
      'Acid and alkali splash resistant',
      'Nylon filament lining',
      'Neoprene coating',
      'Long-style design',
    ],
    specifications: {
      '型号': '3019',
      '品名': '双胶防酸长式工作服',
      '内料': '尼龙长丝布',
      '涂层': '氯丁胶主材',
      '功能': '防酸碱类化学品溶剂喷溅',
      '尺码': 'S/M/L/XL/XXL',
    },
    specificationsEn: {
      'Model': '3019',
      'Product Name': 'Double-Coated Acid-Resistant Long Suit',
      'Lining': 'Nylon Filament Cloth',
      'Coating': 'Neoprene Main Material',
      'Function': 'Acid and Alkali Chemical Splash Protection',
      'Size': 'S/M/L/XL/XXL',
    },
    applications: ['化工行业', '实验室作业', '酸碱环境', '化学品处理'],
    applicationsEn: ['Chemical industry', 'Laboratory work', 'Acid/alkali environments', 'Chemical handling'],
    applicationsAr: ['الصناعة الكيميائية', 'عمل المختبرات', 'بيئات الأحماض والقلويات', 'التعامل مع المواد الكيميائية'],
    applicationsDe: ['Chemische Industrie', 'Laborarbeit', 'Säure-/Laugenumgebungen', 'Chemikalienhandhabung'],
    applicationsEs: ['Industria química', 'Trabajo de laboratorio', 'Entornos de ácidos/álcalis', 'Manejo de químicos'],
    color: '多色可选',
    material: '尼龙长丝布+氯丁胶',
  },
  {
    id: '3088',
    slug: 'acid-resistant-two-piece-suit-3088',
    name: '耐酸分式工作服',
    nameEn: 'Acid-Resistant Two-Piece Suit',
    nameAr: 'بدلة مقاومة للأحماض بقطعتين',
    nameDe: 'Säurebeständiger zweiteiliger Anzug',
    nameEs: 'Traje resistente a ácidos de dos piezas',
    category: 'protective-suits',
    categoryEn: 'Protective Suits',
    images: {
      main: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F3088%E6%AD%A3%E9%9D%A2.jpg&nonce=4c4df7f7-5bb2-4efa-8a72-11b8bdcc0d14&project_id=7620626575964323874&sign=7a7ea85367c773c8ced89dc33d379a7b6c4a6a240fab195936877322c45aaff0',
      side: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F3088%E4%BE%A7%E9%9D%A2.jpg&nonce=ba0221e6-ac46-43d7-acf8-327a0475dba7&project_id=7620626575964323874&sign=b79f753c133a3c71f895eea47da32414b217d1291631d6285e2cfea606e52026',
    },
    description: '耐酸分式工作服，内料采用全棉，涂层为以氯丁胶为主双面涂层，具有防酸碱类化学品溶剂喷溅功能。分体式设计便于穿脱。',
    descriptionEn: 'Acid-resistant two-piece suit with cotton lining and double-sided neoprene-based coating. Provides protection against acid and alkali chemical splashes. Two-piece design for easy wear.',
    descriptionAr: 'بدلة مقاومة للأحماض بقطعتين مع بطانة قطنية وطلاء مزدوج الجوانب من النيوبرين. توفر حماية ضد رشاش المواد الكيميائية الحمضية والقلوية. تصميم بقطعتين لسهولة اللبس.',
    descriptionDe: 'Säurebeständiger zweiteiliger Anzug mit Baumwollfutter und zweiseitiger Neopren-Beschichtung. Bietet Schutz gegen Säure- und Laugenspritzer. Zweiteiliges Design für einfaches Anziehen.',
    descriptionEs: 'Traje resistente a ácidos de dos piezas con forro de algodón y recubrimiento de neopreno de doble cara. Proporciona protección contra salpicaduras de ácidos y álcalis. Diseño de dos piezas para fácil colocación.',
    features: [
      '分体设计',
      '双面涂层',
      '全棉内料',
      '氯丁胶涂层',
      '防酸碱喷溅',
    ],
    featuresEn: [
      'Two-piece design',
      'Double-sided coating',
      'Cotton lining',
      'Neoprene coating',
      'Acid and alkali splash resistant',
    ],
    specifications: {
      '型号': '3088',
      '品名': '耐酸分式工作服',
      '内料': '全棉',
      '涂层': '以氯丁胶为主双面涂层',
      '功能': '防酸碱类化学品溶剂喷溅',
      '尺码': 'S/M/L/XL/XXL',
    },
    specificationsEn: {
      'Model': '3088',
      'Product Name': 'Acid-Resistant Two-Piece Suit',
      'Lining': 'Cotton',
      'Coating': 'Double-sided Neoprene Coating',
      'Function': 'Acid and Alkali Chemical Splash Protection',
      'Size': 'S/M/L/XL/XXL',
    },
    applications: ['化工行业', '实验室作业', '酸碱环境', '化学品处理'],
    applicationsEn: ['Chemical industry', 'Laboratory work', 'Acid/alkali environments', 'Chemical handling'],
    applicationsAr: ['الصناعة الكيميائية', 'عمل المختبرات', 'بيئات الأحماض والقلويات', 'التعامل مع المواد الكيميائية'],
    applicationsDe: ['Chemische Industrie', 'Laborarbeit', 'Säure-/Laugenumgebungen', 'Chemikalienhandhabung'],
    applicationsEs: ['Industria química', 'Trabajo de laboratorio', 'Entornos de ácidos/álcalis', 'Manejo de químicos'],
    color: '多色可选',
    material: '全棉+氯丁胶涂层',
  },
  {
    id: '3112',
    slug: 'one-piece-gas-protection-suit-3112',
    name: '连式防毒衣',
    nameEn: 'One-Piece Gas Protection Suit',
    nameAr: 'بدلة حماية من الغازات بقطعة واحدة',
    nameDe: 'Einteiliger Gasschutzanzug',
    nameEs: 'Traje de protección contra gases de una pieza',
    category: 'protective-suits',
    categoryEn: 'Protective Suits',
    images: {
      main: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F3112%E6%AD%A3%E9%9D%A2.jpg&nonce=f8acf9ea-38ff-4f17-aa92-0c54bd754999&project_id=7620626575964323874&sign=3824dee1ffbf5b894ba456c3026ecf4e498925d1f5c7ded7610d9d2d93c23d0e',
      side: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F3112%E4%BE%A7%E9%9D%A2.jpg&nonce=c2b3a979-9d6b-4850-8752-2606d16f9111&project_id=7620626575964323874&sign=c76721f4556bd3857c6c0e03af0b6ab458091fbb38956fe5680ef400ed557a55',
    },
    description: '连式防毒衣，内料采用全棉，涂层为丁基胶，具有防空气中尘毒功能。可定制防介子气130分钟以上版本。适合化工、危险品处理等作业环境。',
    descriptionEn: 'One-piece gas protection suit with cotton lining and butyl rubber coating. Protects against airborne dust and toxins. Custom version available for over 130 minutes of mustard gas protection. Suitable for chemical and hazardous material handling.',
    descriptionAr: 'بدلة حماية من الغازات بقطعة واحدة مع بطانة قطنية وطلاء مطاط البيوتيل. تحمي من الغبار والسموم المحمولة جواً. نسخة مخصصة متاحة للحماية من غاز الخردل لأكثر من 130 دقيقة.',
    descriptionDe: 'Einteiliger Gasschutzanzug mit Baumwollfutter und Butylkautschuk-Beschichtung. Schützt gegen luftgetragenen Staub und Gifte. Sonderanfertigung für Senfgas-Schutz über 130 Minuten verfügbar.',
    descriptionEs: 'Traje de protección contra gases de una pieza con forro de algodón y recubrimiento de caucho de butilo. Protege contra polvo y toxinas en el aire. Versión personalizada disponible para protección contra gas mostaga superior a 130 minutos.',
    features: [
      '连体设计',
      '丁基胶涂层',
      '全棉内料',
      '防尘毒',
      '可定制防介子气',
    ],
    featuresEn: [
      'One-piece design',
      'Butyl rubber coating',
      'Cotton lining',
      'Dust and toxin protection',
      'Custom mustard gas protection available',
    ],
    specifications: {
      '型号': '3112',
      '品名': '连式防毒衣',
      '内料': '全棉',
      '涂层': '丁基胶',
      '功能': '防空气中尘毒',
      '备注': '防介子气130分钟以上要定制',
      '尺码': 'S/M/L/XL/XXL',
    },
    specificationsEn: {
      'Model': '3112',
      'Product Name': 'One-Piece Gas Protection Suit',
      'Lining': 'Cotton',
      'Coating': 'Butyl Rubber',
      'Function': 'Airborne Dust and Toxin Protection',
      'Note': 'Mustard gas protection over 130 mins requires customization',
      'Size': 'S/M/L/XL/XXL',
    },
    applications: ['化工行业', '危险品处理', '防化作业', '应急救援'],
    applicationsEn: ['Chemical industry', 'Hazardous material handling', 'Chemical defense', 'Emergency rescue'],
    applicationsAr: ['الصناعة الكيميائية', 'التعامل مع المواد الخطرة', 'الدفاع الكيميائي', 'الإنقاذ الطارئ'],
    applicationsDe: ['Chemische Industrie', 'Gefahrguthandhabung', 'Chemische Abwehr', 'Notfallrettung'],
    applicationsEs: ['Industria química', 'Manejo de materiales peligrosos', 'Defensa química', 'Rescate de emergencia'],
    color: '多色可选',
    material: '全棉+丁基胶',
  },
  {
    id: '3113',
    slug: 'gas-protection-suit-with-gloves-boots-3113',
    name: '连式带手套靴防毒衣',
    nameEn: 'One-Piece Gas Protection Suit with Gloves and Boots',
    nameAr: 'بدلة حماية من الغازات بقطعة واحدة مع قفازات وأحذية',
    nameDe: 'Einteiliger Gasschutzanzug mit Handschuhen und Stiefeln',
    nameEs: 'Traje de protección contra gases de una pieza con guantes y botas',
    category: 'protective-suits',
    categoryEn: 'Protective Suits',
    images: {
      main: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F3113%E6%AD%A3%E9%9D%A2.jpg&nonce=1e896fab-b4cb-4103-a587-3a604d8799e7&project_id=7620626575964323874&sign=b8f6cb6a1d31642e01b513fe647b6cb3663593d820318e5c45e68347896544a5',
      side: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F3113%E4%BE%A7%E9%9D%A2.jpg&nonce=642d76fa-445a-4dc4-863a-8954878413ce&project_id=7620626575964323874&sign=39983500d728fce535b3bde0f948f5b41eda86894398dfd55444e97cef1d0b97',
    },
    description: '连式带手套靴防毒衣，内料采用全棉，涂层为丁基胶，集成防护手套和靴子，具有防空气中尘毒功能。可定制防介子气130分钟以上版本。',
    descriptionEn: 'One-piece gas protection suit with integrated gloves and boots. Cotton lining with butyl rubber coating. Protects against airborne dust and toxins. Custom version available for over 130 minutes of mustard gas protection.',
    descriptionAr: 'بدلة حماية من الغازات بقطعة واحدة مع قفازات وأحذية مدمجة. بطانة قطنية مع طلاء مطاط البيوتيل. تحمي من الغبار والسموم المحمولة جواً. نسخة مخصصة متاحة للحماية من غاز الخردل لأكثر من 130 دقيقة.',
    descriptionDe: 'Einteiliger Gasschutzanzug mit integrierten Handschuhen und Stiefeln. Baumwollfutter mit Butylkautschuk-Beschichtung. Schützt gegen luftgetragenen Staub und Gifte. Sonderanfertigung für Senfgas-Schutz über 130 Minuten verfügbar.',
    descriptionEs: 'Traje de protección contra gases de una pieza con guantes y botas integrados. Forro de algodón con recubrimiento de caucho de butilo. Protege contra polvo y toxinas en el aire. Versión personalizada disponible para protección contra gas mostaza superior a 130 minutos.',
    features: [
      '连体设计',
      '集成手套靴',
      '丁基胶涂层',
      '全棉内料',
      '可定制防介子气',
    ],
    featuresEn: [
      'One-piece design',
      'Integrated gloves and boots',
      'Butyl rubber coating',
      'Cotton lining',
      'Custom mustard gas protection available',
    ],
    specifications: {
      '型号': '3113',
      '品名': '连式带手套靴防毒衣',
      '内料': '全棉',
      '涂层': '丁基胶',
      '功能': '防空气中尘毒',
      '备注': '防介子气130分钟以上要定制',
      '尺码': 'S/M/L/XL/XXL',
    },
    specificationsEn: {
      'Model': '3113',
      'Product Name': 'One-Piece Gas Protection Suit with Gloves and Boots',
      'Lining': 'Cotton',
      'Coating': 'Butyl Rubber',
      'Function': 'Airborne Dust and Toxin Protection',
      'Note': 'Mustard gas protection over 130 mins requires customization',
      'Size': 'S/M/L/XL/XXL',
    },
    applications: ['化工行业', '危险品处理', '防化作业', '应急救援'],
    applicationsEn: ['Chemical industry', 'Hazardous material handling', 'Chemical defense', 'Emergency rescue'],
    applicationsAr: ['الصناعة الكيميائية', 'التعامل مع المواد الخطرة', 'الدفاع الكيميائي', 'الإنقاذ الطارئ'],
    applicationsDe: ['Chemische Industrie', 'Gefahrguthandhabung', 'Chemische Abwehr', 'Notfallrettung'],
    applicationsEs: ['Industria química', 'Manejo de materiales peligrosos', 'Defensa química', 'Rescate de emergencia'],
    color: '多色可选',
    material: '全棉+丁基胶',
  },
  {
    id: '3116',
    slug: 'fully-enclosed-gas-protection-suit-3116',
    name: '全封闭连式防毒衣',
    nameEn: 'Fully Enclosed Gas Protection Suit',
    nameAr: 'بدلة حماية من الغازات مغلقة بالكامل',
    nameDe: 'Vollständig geschlossener Gasschutzanzug',
    nameEs: 'Traje de protección contra gases completamente cerrado',
    category: 'protective-suits',
    categoryEn: 'Protective Suits',
    images: {
      main: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F3116%E6%AD%A3%E9%9D%A2.jpeg&nonce=8d09e7d7-8bce-44fc-a443-8007529d5c57&project_id=7620626575964323874&sign=6a7096e5f59950a00a409b2fef26a6f7e99ff0b0ee920cff3a4bd59e00be7554',
      side: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F3116%E4%BE%A7%E9%9D%A2.jpeg&nonce=b65c3f5a-0713-4910-a69f-60073dd19234&project_id=7620626575964323874&sign=89c4d76fcc6721c1bcda850894438a01693a9747b564fd1e99065c756b446ff1',
    },
    description: '全封闭连式防毒衣，内料采用涤棉，涂层为以氯丁胶为主双面涂层，采用空气接入式设计，具有防空气中尘毒功能。可定制防介子气130分钟以上版本。',
    descriptionEn: 'Fully enclosed gas protection suit with polyester-cotton lining and double-sided neoprene-based coating. Air-fed design for protection against airborne dust and toxins. Custom version available for over 130 minutes of mustard gas protection.',
    descriptionAr: 'بدلة حماية من الغازات مغلقة بالكامل مع بطانة من البوليستر-القطن وطلاء مزدوج الجوانب من النيوبرين. تصميم بتغذية هوائية للحماية من الغبار والسموم المحمولة جواً. نسخة مخصصة متاحة للحماية من غاز الخردل لأكثر من 130 دقيقة.',
    descriptionDe: 'Vollständig geschlossener Gasschutzanzug mit Polyester-Baumwoll-Futter und zweiseitiger Neopren-Beschichtung. Luftgespeistes Design zum Schutz gegen luftgetragenen Staub und Gifte. Sonderanfertigung für Senfgas-Schutz über 130 Minuten verfügbar.',
    descriptionEs: 'Traje de protección contra gases completamente cerrado con forro de poliéster-algodón y recubrimiento de neopreno de doble cara. Diseño con alimentación de aire para protección contra polvo y toxinas en el aire. Versión personalizada disponible para protección contra gas mostaza superior a 130 minutos.',
    features: [
      '全封闭设计',
      '空气接入式',
      '双面氯丁胶涂层',
      '涤棉内料',
      '可定制防介子气',
    ],
    featuresEn: [
      'Fully enclosed design',
      'Air-fed system',
      'Double-sided neoprene coating',
      'Polyester-cotton lining',
      'Custom mustard gas protection available',
    ],
    specifications: {
      '型号': '3116',
      '品名': '全封闭连式防毒衣',
      '内料': '涤棉',
      '涂层': '以氯丁胶为主双面涂层',
      '功能': '防空气中尘毒空气接入式',
      '备注': '防介子气130分钟以上要定制',
      '尺码': 'S/M/L/XL/XXL',
    },
    specificationsEn: {
      'Model': '3116',
      'Product Name': 'Fully Enclosed Gas Protection Suit',
      'Lining': 'Polyester-Cotton',
      'Coating': 'Double-sided Neoprene Coating',
      'Function': 'Air-fed Airborne Dust and Toxin Protection',
      'Note': 'Mustard gas protection over 130 mins requires customization',
      'Size': 'S/M/L/XL/XXL',
    },
    applications: ['化工行业', '危险品处理', '防化作业', '应急救援'],
    applicationsEn: ['Chemical industry', 'Hazardous material handling', 'Chemical defense', 'Emergency rescue'],
    applicationsAr: ['الصناعة الكيميائية', 'التعامل مع المواد الخطرة', 'الدفاع الكيميائي', 'الإنقاذ الطارئ'],
    applicationsDe: ['Chemische Industrie', 'Gefahrguthandhabung', 'Chemische Abwehr', 'Notfallrettung'],
    applicationsEs: ['Industria química', 'Manejo de materiales peligrosos', 'Defensa química', 'Rescate de emergencia'],
    color: '多色可选',
    material: '涤棉+氯丁胶',
  },
  {
    id: '3121',
    slug: 'heat-resistant-gas-protection-suit-3121',
    name: '全封闭分式隔热防毒衣',
    nameEn: 'Fully Enclosed Heat-Resistant Gas Protection Suit',
    nameAr: 'بدلة حماية من الغازات مقاومة للحرارة مغلقة بالكامل',
    nameDe: 'Vollständig geschlossener hitzebeständiger Gasschutzanzug',
    nameEs: 'Traje de protección contra gases resistente al calor completamente cerrado',
    category: 'protective-suits',
    categoryEn: 'Protective Suits',
    images: {
      main: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F3121%E6%AD%A3%E9%9D%A2.jpg&nonce=4ca6abf5-7795-47f3-b7ba-b9a06b65bca2&project_id=7620626575964323874&sign=92f1e7671778a3c42f85a77b2d8539eced8375592f6c92ede44af53fc575bb64',
      side: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F3121%E4%BE%A7%E9%9D%A2.jpg&nonce=16048c1b-8af1-4784-8ad2-76c328b5b65a&project_id=7620626575964323874&sign=6b3e544f080bdd381fc5da5534971522e530c5e478f0c613cb1c75ec5822f2f7',
    },
    description: '全封闭分式隔热防毒衣，内料采用全棉，涂层为丁基胶，采用空气接入式设计，具有隔热防空气中尘毒功能。适合高温有毒环境作业。',
    descriptionEn: 'Fully enclosed heat-resistant gas protection suit with cotton lining and butyl rubber coating. Air-fed design provides heat insulation and protection against airborne dust and toxins. Suitable for high-temperature toxic environments.',
    descriptionAr: 'بدلة حماية من الغازات مقاومة للحرارة مغلقة بالكامل مع بطانة قطنية وطلاء مطاط البيوتيل. تصميم بتغذية هوائية يوفر عزل حراري وحماية من الغبار والسموم المحمولة جواً. مناسبة لبيئات سامة عالية الحرارة.',
    descriptionDe: 'Vollständig geschlossener hitzebeständiger Gasschutzanzug mit Baumwollfutter und Butylkautschuk-Beschichtung. Luftgespeistes Design bietet Wärmedämmung und Schutz gegen luftgetragenen Staub und Gifte. Geeignet für heiße giftige Umgebungen.',
    descriptionEs: 'Traje de protección contra gases resistente al calor completamente cerrado con forro de algodón y recubrimiento de caucho de butilo. Diseño con alimentación de aire proporciona aislamiento térmico y protección contra polvo y toxinas en el aire. Adecuado para entornos tóxicos de alta temperatura.',
    features: [
      '全封闭设计',
      '隔热功能',
      '空气接入式',
      '丁基胶涂层',
      '分体式结构',
    ],
    featuresEn: [
      'Fully enclosed design',
      'Heat insulation',
      'Air-fed system',
      'Butyl rubber coating',
      'Two-piece structure',
    ],
    specifications: {
      '型号': '3121',
      '品名': '全封闭分式隔热防毒衣',
      '内料': '全棉',
      '涂层': '丁基胶',
      '功能': '隔热防空气中尘毒空气接入式',
      '尺码': 'S/M/L/XL/XXL',
    },
    specificationsEn: {
      'Model': '3121',
      'Product Name': 'Fully Enclosed Heat-Resistant Gas Protection Suit',
      'Lining': 'Cotton',
      'Coating': 'Butyl Rubber',
      'Function': 'Heat-insulated Air-fed Dust and Toxin Protection',
      'Size': 'S/M/L/XL/XXL',
    },
    applications: ['高温有毒环境', '冶金炉前作业', '消防高温救援', '玻璃制造'],
    applicationsEn: ['High-temperature toxic environments', 'Metallurgical furnace work', 'Fire rescue', 'Glass manufacturing'],
    applicationsAr: ['بيئات سامة عالية الحرارة', 'عمل الأفران المعدنية', 'الإنقاذ من الحرائق', 'صناعة الزجاج'],
    applicationsDe: ['Heiße giftige Umgebungen', 'Metallurgische Ofenarbeit', 'Feuerwehrrettung', 'Glasherstellung'],
    applicationsEs: ['Entornos tóxicos de alta temperatura', 'Trabajo en hornos metalúrgicos', 'Rescate de incendios', 'Fabricación de vidrio'],
    color: '多色可选',
    material: '全棉+丁基胶',
  },
  {
    id: '3218',
    slug: 'chemical-resistant-flame-retardant-suit-3218',
    name: '双胶防化阻燃连式工作服带手套靴',
    nameEn: 'Double-Coated Chemical-Resistant Flame-Retardant Suit',
    nameAr: 'بدلة مقاومة للكيماويات واللهب مزدوجة الطلاء',
    nameDe: 'Doppelt beschichteter chemikalienbeständiger flammhemmender Anzug',
    nameEs: 'Traje resistente a químicos y llamas de doble recubrimiento',
    category: 'protective-suits',
    categoryEn: 'Protective Suits',
    images: {
      main: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F3218%E6%AD%A3%E9%9D%A2.jpg&nonce=8c5d49cb-4c5e-4fe6-88b1-22f7427d83a0&project_id=7620626575964323874&sign=eb94a303ad43394c3a8a8ac54c835b6508008b7fa4e7d2d636eb54f04d77c1da',
      side: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F3218%E4%BE%A7%E9%9D%A2.jpg&nonce=91db0c9a-8dde-470a-857c-5ab515525d60&project_id=7620626575964323874&sign=7a4250ee788076d9867651db016feaea1fd647d59b3f74e9c6bd033192d832c9',
    },
    description: '双胶防化阻燃连式工作服带手套靴，内料采用尼龙长丝布，涂层为氯丁胶主材。防多种化学品酸类、油类和溶剂类，除手套外衣服靴阻燃，可增加抗静电功能。',
    descriptionEn: 'Double-coated chemical-resistant flame-retardant suit with integrated gloves and boots. Nylon filament cloth lining with neoprene coating. Protects against acids, oils and solvents. Flame-retardant body and boots, anti-static option available.',
    descriptionAr: 'بدلة مقاومة للكيماويات واللهب مزدوجة الطلاء مع قفازات وأحذية مدمجة. بطانة من قماش خيوط النايلون مع طلاء النيوبرين. تحمي من الأحماض والزيوت والمذيبات. الجسم والأحذية مقاومة للهب، خيار مضاد للكهرباء الساكنة متاح.',
    descriptionDe: 'Doppelt beschichteter chemikalienbeständiger flammhemmender Anzug mit integrierten Handschuhen und Stiefeln. Nylon-Filamentgewebe-Futter mit Neopren-Beschichtung. Schützt gegen Säuren, Öle und Lösungsmittel. Flammhemmender Körper und Stiefel, antistatische Option verfügbar.',
    descriptionEs: 'Traje resistente a químicos y llamas de doble recubrimiento con guantes y botas integrados. Forro de tela de filamento de nailon con recubrimiento de neopreno. Protege contra ácidos, aceites y disolventes. Cuerpo y botas resistentes a llamas, opción antiestática disponible.',
    features: [
      '双胶涂层',
      '防化阻燃',
      '集成手套靴',
      '尼龙长丝内料',
      '可选抗静电功能',
    ],
    featuresEn: [
      'Double-coated design',
      'Chemical and flame resistant',
      'Integrated gloves and boots',
      'Nylon filament lining',
      'Anti-static option available',
    ],
    specifications: {
      '型号': '3218',
      '品名': '双胶防化阻燃连式工作服带手套靴',
      '内料': '尼龙长丝布',
      '涂层': '氯丁胶主材',
      '功能': '防多种化学品酸类、油类和溶剂类',
      '特点': '除手套外衣服靴阻燃，可增加抗静电功能',
      '尺码': 'S/M/L/XL/XXL',
    },
    specificationsEn: {
      'Model': '3218',
      'Product Name': 'Double-Coated Chemical-Resistant Flame-Retardant Suit',
      'Lining': 'Nylon Filament Cloth',
      'Coating': 'Neoprene Main Material',
      'Function': 'Multiple Chemical/Acid/Oil/Solvent Protection',
      'Features': 'Flame-retardant body and boots, anti-static optional',
      'Size': 'S/M/L/XL/XXL',
    },
    applications: ['化工行业', '危险品处理', '消防作业', '化学品泄漏应急'],
    applicationsEn: ['Chemical industry', 'Hazardous material handling', 'Firefighting', 'Chemical spill response'],
    applicationsAr: ['الصناعة الكيميائية', 'التعامل مع المواد الخطرة', 'مكافحة الحرائق', 'الاستجابة لتسرب المواد الكيميائية'],
    applicationsDe: ['Chemische Industrie', 'Gefahrguthandhabung', 'Feuerwehr', 'Chemieunfallreaktion'],
    applicationsEs: ['Industria química', 'Manejo de materiales peligrosos', 'Bomberos', 'Respuesta a derrames químicos'],
    color: '多色可选',
    material: '尼龙长丝布+氯丁胶',
  },
  // ==================== 工装系列 ====================
  {
    id: '5061',
    slug: 'double-coated-wading-pants-5061',
    name: '双胶下水裤',
    nameEn: 'Double-Coated Wading Pants',
    nameAr: 'بنطلون خوض مزدوج الطلاء',
    nameDe: 'Doppelt beschichtete Watthose',
    nameEs: 'Pantalones de vadeo de doble recubrimiento',
    category: 'workwear',
    categoryEn: 'Workwear Series',
    images: {
      main: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F5061%E6%AD%A3%E9%9D%A2.jpg&nonce=adeff28c-ead6-4a98-ad44-93343ab56b11&project_id=7620626575964323874&sign=01d1407864a54e839992b0e40be138e0b96967268c75e6818307dd567778f420',
      side: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F5061%E4%BE%A7%E9%9D%A2.jpg&nonce=f69b6abf-4e1a-4c82-91be-c22f142f09ca&project_id=7620626575964323874&sign=8279e7f5dafabb74629d448cc0158b0f474ef7ca076bdb5de0d8ec8f82504e35',
    },
    description: '双胶下水裤，内料采用全棉，涂层为双面氯丁混合胶，静水压≥100kPa。适合水产养殖、河道作业、渔业捕捞等水下作业环境。',
    descriptionEn: 'Double-coated wading pants with cotton lining and double-sided neoprene mixed rubber coating. Hydrostatic pressure ≥100kPa. Suitable for aquaculture, river operations, and fishing.',
    descriptionAr: 'بنطلون خوض مزدوج الطلاء مع بطانة قطنية وطلاء مطاط النيوبرين المختلط مزدوج الجوانب. ضغط هيدروستاتيكي ≥100 كيلو باسكال. مناسب لتربية الأحياء المائية وعمليات الأنهار والصيد.',
    descriptionDe: 'Doppelt beschichtete Watthosen mit Baumwollfutter und zweiseitiger Neopren-Mischgummi-Beschichtung. Hydrostatischer Druck ≥100 kPa. Geeignet für Aquakultur, Flussarbeiten und Fischerei.',
    descriptionEs: 'Pantalones de vadeo de doble recubrimiento con forro de algodón y recubrimiento de goma mezclada de neopreno de doble cara. Presión hidrostática ≥100 kPa. Adecuados para acuicultura, operaciones fluviales y pesca.',
    features: [
      '双面涂层',
      '高静水压',
      '全棉内料',
      '氯丁混合胶',
      '背带设计',
    ],
    featuresEn: [
      'Double-sided coating',
      'High hydrostatic pressure',
      'Cotton lining',
      'Neoprene mixed rubber',
      'Overall design',
    ],
    specifications: {
      '型号': '5061',
      '品名': '双胶下水裤',
      '内料': '全棉',
      '涂层': '双面氯丁混合胶',
      '静水压': '≥100 kPa',
      '尺码': 'S/M/L/XL/XXL',
    },
    specificationsEn: {
      'Model': '5061',
      'Product Name': 'Double-Coated Wading Pants',
      'Lining': 'Cotton',
      'Coating': 'Double-sided Neoprene Mixed Rubber',
      'Hydrostatic Pressure': '≥100 kPa',
      'Size': 'S/M/L/XL/XXL',
    },
    applications: ['水产养殖', '河道作业', '渔业捕捞', '水下施工'],
    applicationsEn: ['Aquaculture', 'River operations', 'Fishing', 'Underwater construction'],
    applicationsAr: ['تربية الأحياء المائية', 'عمليات الأنهار', 'الصيد', 'البناء تحت الماء'],
    applicationsDe: ['Aquakultur', 'Flussarbeiten', 'Fischerei', 'Unterwasserbau'],
    applicationsEs: ['Acuicultura', 'Operaciones fluviales', 'Pesca', 'Construcción submarina'],
    color: '多色可选',
    material: '全棉+氯丁混合胶',
  },
  {
    id: '5-2',
    slug: 'fluorescent-green-police-suit',
    name: '莹光绿警服',
    nameEn: 'Fluorescent Green Police Suit',
    nameAr: 'بدلة شرطة خضراء فلورسنت',
    nameDe: 'Fluoreszierender grüner Polizei-Anzug',
    nameEs: 'Traje de policía verde fluorescente',
    category: 'workwear',
    categoryEn: 'Workwear Series',
    images: {
      main: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F5-2%E6%AD%A3%E9%9D%A2.jpeg&nonce=df1a4148-eaef-4df0-8827-48d38d07a17e&project_id=7620626575964323874&sign=a54d9ee7bd22d94e81ee245e3a3a173e2a0d1c8036d5d86db68c3b446d35ed1a',
      side: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F5-2%E4%BE%A7%E9%9D%A2.jpeg&nonce=2b9a4454-7bd7-45d9-a33e-72f9ae14cea5&project_id=7620626575964323874&sign=800c5e8ae8e8d5f7b0b2d165d7c2a271aabc6c9179daccc5bc9d099d345a76fd',
    },
    description: '莹光绿警服，面料采用240T尼龙塔丝绒表面泼水处理，涂层为环保PU，内里为针织网布。配备3M反光带，适合交警、安保等户外作业。',
    descriptionEn: 'Fluorescent green police suit with 240T nylon taffeta fabric with water-repellent treatment, environmental PU coating, and knitted mesh lining. Features 3M reflective strips. Suitable for traffic police, security and outdoor work.',
    descriptionAr: 'بدلة شرطة خضراء فلورسنت مع قماش نايلون تافيتا 240T مع معالجة طاردة للماء، طلاء PU صديق للبيئة، وبطانة شبكة محيكة. مجهزة بشرائط عاكسة 3M. مناسبة لشرطة المرور والأمن والعمل في الهواء الطلق.',
    descriptionDe: 'Fluoreszierender grüner Polizei-Anzug aus 240T Nylon-Taffeta-Gewebe mit wasserabweisender Behandlung, umweltfreundlicher PU-Beschichtung und gestricktem Netzfutter. Mit 3M-Reflektorstreifen. Geeignet für Verkehrspolizei, Sicherheit und Außenarbeit.',
    descriptionEs: 'Traje de policía verde fluorescente con tela de tafetán de nailon 240T con tratamiento repelente al agua, recubrimiento de PU ecológico y forro de malla de punto. Cuenta con tiras reflectantes 3M. Adecuado para policía de tráfico, seguridad y trabajo al aire libre.',
    features: [
      '莹光绿高可视',
      '3M反光带',
      '尼龙塔丝绒面料',
      '环保PU涂层',
      '针织网布内里',
    ],
    featuresEn: [
      'High-visibility fluorescent green',
      '3M reflective strips',
      'Nylon taffeta fabric',
      'Environmental PU coating',
      'Knitted mesh lining',
    ],
    specifications: {
      '型号': '5-2',
      '品名': '莹光绿警服',
      '面料': '240T尼龙塔丝绒表面泼水处理',
      '涂层': '环保PU',
      '内里': '针织网布(白色)',
      '反光带亮度': '≥500 (3M反光带)',
      '尺码': 'S/M/L/XL/XXL',
    },
    specificationsEn: {
      'Model': '5-2',
      'Product Name': 'Fluorescent Green Police Suit',
      'Fabric': '240T Nylon Taffeta Water-Repellent',
      'Coating': 'Environmental PU',
      'Lining': 'Knitted Mesh (White)',
      'Reflective Strip Brightness': '≥500 (3M Reflective)',
      'Size': 'S/M/L/XL/XXL',
    },
    applications: ['交警执勤', '安保作业', '户外指挥', '道路施工'],
    applicationsEn: ['Traffic police duty', 'Security work', 'Outdoor direction', 'Road construction'],
    applicationsAr: ['واجب شرطة المرور', 'عمل الأمن', 'التوجيه في الهواء الطلق', 'بناء الطرق'],
    applicationsDe: ['Verkehrspolizeidienst', 'Sicherheitsarbeit', 'Außenanweisung', 'Straßenbau'],
    applicationsEs: ['Servicio de policía de tráfico', 'Trabajo de seguridad', 'Dirección al aire libre', 'Construcción de carreteras'],
    color: '莹光绿',
    material: '尼龙塔丝绒+PU涂层',
  },
  {
    id: '5-5',
    slug: 'spring-yarn-splicing-suit',
    name: '春亚纺相拼色套装',
    nameEn: 'Spring Yarn Splicing Suit',
    nameAr: 'بدلة ألوان متجانبة من قماش الربيع',
    nameDe: 'Frühlingsgarn-Farbmisch-Anzug',
    nameEs: 'Traje de colores combinados de tejido de primavera',
    category: 'workwear',
    categoryEn: 'Workwear Series',
    images: {
      main: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F5-5%E6%AD%A3%E9%9D%A2.jpeg&nonce=7d02a60b-9c17-44ea-9f7e-119635abe2f8&project_id=7620626575964323874&sign=eb1d06ccd8fe9c39f6789b39c1b46b4a3759a410250c83276dcfa581e6361498',
      side: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F5-5%E4%BE%A7%E9%9D%A2.jpg&nonce=bf570499-5671-4852-b0eb-22d32c29ac3d&project_id=7620626575964323874&sign=7d7cc744082001764c95a969278e1fb224cb61f82f645081686a006556dded89',
    },
    description: '春亚纺相拼色套装，面料采用240T春亚纺，涂层为环保PVC，内里为190T涤纶。时尚相拼色设计，适合户外作业。',
    descriptionEn: 'Spring yarn splicing color suit with 240T spring yarn fabric, environmental PVC coating, and 190T polyester lining. Stylish splicing design suitable for outdoor work.',
    descriptionAr: 'بدلة ألوان متجانبة من قماش الربيع مع قماش ربيعي 240T، طلاء PVC صديق للبيئة، وبطانة بوليستر 190T. تصميم ألوان متجانبة عصري مناسب للعمل في الهواء الطلق.',
    descriptionDe: 'Frühlingsgarn-Farbmisch-Anzug aus 240T Frühlingsgarn-Gewebe, umweltfreundlicher PVC-Beschichtung und 190T Polyester-Futter. Stilvolles Farbmisch-Design geeignet für Außenarbeit.',
    descriptionEs: 'Traje de colores combinados de tejido de primavera con tela de hilo de primavera 240T, recubrimiento de PVC ecológico y forro de poliéster 190T. Diseño de combinación de colores elegante adecuado para trabajo al aire libre.',
    features: [
      '相拼色设计',
      '240T春亚纺面料',
      '环保PVC涂层',
      '190T涤纶内里',
      '时尚外观',
    ],
    featuresEn: [
      'Splicing color design',
      '240T spring yarn fabric',
      'Environmental PVC coating',
      '190T polyester lining',
      'Stylish appearance',
    ],
    specifications: {
      '型号': '5-5',
      '品名': '春亚纺相拼色套装',
      '面料': '240T春亚纺',
      '涂层': '环保PVC',
      '内里': '190T涤纶',
      '静水压': '≥50 kPa',
      '尺码': 'S/M/L/XL/XXL',
    },
    specificationsEn: {
      'Model': '5-5',
      'Product Name': 'Spring Yarn Splicing Suit',
      'Fabric': '240T Spring Yarn',
      'Coating': 'Environmental PVC',
      'Lining': '190T Polyester',
      'Hydrostatic Pressure': '≥50 kPa',
      'Size': 'S/M/L/XL/XXL',
    },
    applications: ['户外作业', '建筑施工', '设备维护', '日常防护'],
    applicationsEn: ['Outdoor work', 'Construction', 'Equipment maintenance', 'Daily protection'],
    applicationsAr: ['العمل في الهواء الطلق', 'البناء', 'صيانة المعدات', 'الحماية اليومية'],
    applicationsDe: ['Außenarbeit', 'Bauwesen', 'Gerätewartung', 'Täglicher Schutz'],
    applicationsEs: ['Trabajo al aire libre', 'Construcción', 'Mantenimiento de equipos', 'Protección diaria'],
    color: '相拼色',
    material: '春亚纺+PVC涂层',
  },
  {
    id: '6016',
    slug: 'split-apron-sleeve-set',
    name: '分体式围裙袖套套装',
    nameEn: 'Split Apron & Sleeve Set',
    nameAr: 'طقم مريولة وأكمام منفصل',
    nameDe: 'Getrenntes Schürzen- und Ärmel-Set',
    nameEs: 'Set de delantal y mangas separados',
    category: 'workwear',
    categoryEn: 'Workwear Series',
    images: {
      main: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F6016%E6%AD%A3%E9%9D%A2.jpg&nonce=3e98e2af-86b7-43db-98da-11dabb238403&project_id=7620626575964323874&sign=72347bd8bf96adef019d6f35f949e88e27ef9088fc9dd0f50ecfe0b77af24933',
      side: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F6016%E4%BE%A7%E9%9D%A2.jpg&nonce=01a6f28f-2c93-4a71-87d3-72a856a4a449&project_id=7620626575964323874&sign=fcbba653458fc574d3730138dacfcb2cc882e47c5432036e2b4956a89bc2eb60',
    },
    description: '挂脖式长款围裙搭配独立挂肩式防护袖套，围裙长度覆盖到大腿下部。适合餐饮后厨、屠宰加工、机械油污清理等场景，方便穿脱，不限制上半身动作。',
    descriptionEn: 'Neck-hanging long apron paired with separate shoulder-hanging protective sleeves. Apron length covers to lower thigh. Suitable for kitchen, slaughterhouse, and mechanical oil cleaning. Easy to put on and take off.',
    descriptionAr: 'مريولة طويلة معلقة بالرقبة مع أكمام واقية منفصلة معلقة بالكتف. طول المريولة يصل إلى أسفل الفخذ. مناسبة للمطبخ والمسلخ وتنظيف الزيوت الميكانيكية. سهلة اللبس والخلع.',
    descriptionDe: 'Um den Hals hängende lange Schürze mit separaten schultergehängten Schutzmanschetten. Schürzenlänge bis unter den Oberschenkel. Geeignet für Küche, Schlachthof und mechanische Öreinigung. Leicht an- und auszuziehen.',
    descriptionEs: 'Delantal largo colgado del cuello con mangas protectoras separadas colgadas del hombro. Longitud del delantal hasta el muslo inferior. Adecuado para cocina, matadero y limpieza de aceite mecánico. Fácil de poner y quitar.',
    features: [
      '挂脖式围裙',
      '独立袖套设计',
      '长款保护',
      '防水防油',
      '易于穿脱',
    ],
    featuresEn: [
      'Neck-hanging apron',
      'Separate sleeve design',
      'Long-length protection',
      'Water and oil resistant',
      'Easy to wear and remove',
    ],
    specifications: {
      '材质': '橡胶/PVC',
      '颜色': '黑色',
      '围裙长度': '约90cm',
      '袖套长度': '长袖',
    },
    specificationsEn: {
      'Material': 'Rubber/PVC',
      'Color': 'Black',
      'Apron Length': 'Approx. 90cm',
      'Sleeve Length': 'Long Sleeve',
    },
    applications: ['餐饮后厨', '屠宰加工', '机械维修', '油污清理'],
    applicationsEn: ['Commercial kitchen', 'Slaughterhouse', 'Mechanical maintenance', 'Oil cleaning'],
    applicationsAr: ['المطبخ التجاري', 'المسلخ', 'الصيانة الميكانيكية', 'تنظيف الزيوت'],
    applicationsDe: ['Gewerbeküche', 'Schlachthof', 'Mechanische Wartung', 'Ölreinigung'],
    applicationsEs: ['Cocina comercial', 'Matadero', 'Mantenimiento mecánico', 'Limpieza de aceite'],
    color: '黑色',
    material: '橡胶/PVC',
  },
  // ==================== 雨衣系列 ====================
  {
    id: '1-1',
    slug: 'anti-static-work-suit',
    name: '抗静电工作套装',
    nameEn: 'Anti-Static Work Suit',
    nameAr: 'بدلة عمل مضادة للكهرباء الساكنة',
    nameDe: 'Antistatischer Arbeitsanzug',
    nameEs: 'Traje de trabajo antiestático',
    category: 'rainwear',
    categoryEn: 'Rainwear Series',
    images: {
      main: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F1-1%E9%A6%96%E5%9B%BE.jpg&nonce=1e11b54b-8950-4dba-b5c5-d87af845c404&project_id=7620626575964323874&sign=2cca2e314202ccb544f3703df61eff8040a07fb31902bfc83bc45d4b572ab83a',
      side: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F1-1%E4%BE%A7%E9%9D%A2.jpg&nonce=ff2e659e-5ac7-4530-b6b6-f6d0bd3799eb&project_id=7620626575964323874&sign=891e8af53fb8cdea9412f67d43e0c5be682e0ab5f6cb6cc363be1dde00e711b2',
      additional: ['https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F1-1%E6%AD%A3%E9%9D%A2.jpg&nonce=82409235-dfcc-4186-b8eb-282b2fdd27f4&project_id=7620626575964323874&sign=6cc2a1b95c27a29735f9afcc4a731fea31a0699763f1842a129f85b5c6a46fed'],
    },
    description: '抗静电工作套装，面料采用100D涤纶与进口导电丝混织表面泼水处理，涂层为环保PVC，内里为涤纶190T静电布。具有抗静电功能，适合电子、石化等对静电敏感的作业环境。',
    descriptionEn: 'Anti-static work suit with 100D polyester and imported conductive wire blended fabric with water-repellent treatment, environmental PVC coating, and 190T anti-static polyester lining. Anti-static function suitable for electronics, petrochemical and other static-sensitive work environments.',
    descriptionAr: 'بدلة عمل مضادة للكهرباء الساكنة مع قماش بوليستر 100D وسلك موصل مستورد منسوج مع معالجة طاردة للماء، طلاء PVC صديق للبيئة، وبطانة بوليستر 190T مضادة للكهرباء الساكنة. وظيفة مضادة للكهرباء الساكنة مناسبة للإلكترونيات والبتروكيماويات وبيئات العمل الحساسة للكهرباء الساكنة.',
    descriptionDe: 'Antistatischer Arbeitsanzug aus 100D Polyester und importiertem leitfähigem Draht-Mischgewebe mit wasserabweisender Behandlung, umweltfreundlicher PVC-Beschichtung und 190T antistatischem Polyester-Futter. Antistatische Funktion geeignet für Elektronik, Petrochemie und andere statikempfindliche Arbeitsumgebungen.',
    descriptionEs: 'Traje de trabajo antiestático con tela de poliéster 100D y alambre conductor importado mezclado con tratamiento repelente al agua, recubrimiento de PVC ecológico y forro de poliéster 190T antiestático. Función antiestática adecuada para electrónica, petroquímica y otros entornos de trabajo sensibles a la estática.',
    features: [
      '抗静电功能',
      '导电丝混织',
      '环保PVC涂层',
      '静电布内里',
      '高亮反光带',
    ],
    featuresEn: [
      'Anti-static function',
      'Conductive wire blended',
      'Environmental PVC coating',
      'Anti-static lining',
      'High-brightness reflective strips',
    ],
    specifications: {
      '型号': '1-1',
      '品名': '抗静电工作套装',
      '面料': '100D涤纶与进口导电丝混织表面泼水处理',
      '涂层': '环保PVC',
      '内里': '涤纶190T静电布',
      '静水压': '≥50 kPa',
      '反光带亮度': '≥500 (欧标)',
      '尺码': 'S/M/L/XL/XXL',
    },
    specificationsEn: {
      'Model': '1-1',
      'Product Name': 'Anti-Static Work Suit',
      'Fabric': '100D Polyester with Conductive Wire Water-Repellent',
      'Coating': 'Environmental PVC',
      'Lining': '190T Anti-Static Polyester',
      'Hydrostatic Pressure': '≥50 kPa',
      'Reflective Strip Brightness': '≥500 (EN Standard)',
      'Size': 'S/M/L/XL/XXL',
    },
    applications: ['路政作业', '救援工作', '户外施工', '日常出行'],
    applicationsEn: ['Road maintenance', 'Rescue work', 'Outdoor construction', 'Daily commuting'],
    applicationsAr: ['صيانة الطرق', 'عمل الإنقاذ', 'البناء في الهواء الطلق', 'التنقل اليومي'],
    applicationsDe: ['Straßenwartung', 'Rettungsarbeit', 'Außenbau', 'Tägliches Pendeln'],
    applicationsEs: ['Mantenimiento vial', 'Trabajo de rescate', 'Construcción al aire libre', 'Desplazamiento diario'],
    color: '浅灰蓝色',
    material: 'PVC防水面料',
  },
  {
    id: '1-6',
    slug: 'mine-waterproof-cotton-coat',
    name: '矿井防水棉衣',
    nameEn: 'Mine Waterproof Cotton Coat',
    nameAr: 'معطف قطني مقاوم للماء للمناجم',
    nameDe: 'Minen-Wasserdichter Baumwollmantel',
    nameEs: 'Abrigo de algodón impermeable para minas',
    category: 'rainwear',
    categoryEn: 'Rainwear Series',
    images: {
      main: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F1-6%E9%98%B2%E5%AF%92%E6%9C%8D%E6%AD%A3%E9%9D%A2.jpg&nonce=1e481a72-1d6b-4e53-ab31-940329681411&project_id=7620626575964323874&sign=e12f6d0878dee36b23e339c1ae64656cdae1b2c081e72c5bef38a3b03fa5e116',
      side: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F1-6%E9%98%B2%E5%AF%92%E6%9C%8D%E4%BE%A7%E9%9D%A2.jpg&nonce=529ed43e-3f66-4c0e-a443-e01d275449b5&project_id=7620626575964323874&sign=cad90c4fcc71d2709d2ff02dc60082b873ea52c0c607bb0fbd8f404daa40848c',
    },
    description: '矿井防水棉衣，面料采用210T春亚纺，涂层为环保PVC，内里为涤纶行缝棉，静水压≥50kPa，反光带亮度≥500(欧标)。适合矿井、隧道等潮湿寒冷作业环境。',
    descriptionEn: 'Mine waterproof cotton coat with 210T spring yarn fabric, environmental PVC coating, and polyester quilted cotton lining. Hydrostatic pressure ≥50kPa, reflective strip brightness ≥500 (EN standard). Suitable for mines, tunnels and other damp cold environments.',
    descriptionAr: 'معطف قطني مقاوم للماء للمناجم مع قماش ربيعي 210T، طلاء PVC صديق للبيئة، وبطانة قطن محيكة من البوليستر. ضغط هيدروستاتيكي ≥50 كيلو باسكال، سطوع الشرائط العاكسة ≥500 (معيار أوروبي). مناسب للمناجم والأنفاق وبيئات العمل الباردة الرطبة.',
    descriptionDe: 'Minen-Wasserdichter Baumwollmantel aus 210T Frühlingsgarn-Gewebe, umweltfreundlicher PVC-Beschichtung und Polyester-Steppbaumwoll-Futter. Hydrostatischer Druck ≥50 kPa, Reflektorstreifen-Helligkeit ≥500 (EN-Norm). Geeignet für Minen, Tunnel und andere feuchte kalte Umgebungen.',
    descriptionEs: 'Abrigo de algodón impermeable para minas con tela de hilo de primavera 210T, recubrimiento de PVC ecológico y forro de algodón acolchado de poliéster. Presión hidrostática ≥50 kPa, brillo de tira reflectante ≥500 (norma EN). Adecuado para minas, túneles y otros entornos fríos y húmedos.',
    features: [
      '防水保暖',
      '行缝棉内里',
      '高亮反光带',
      '春亚纺面料',
      '环保PVC涂层',
    ],
    featuresEn: [
      'Waterproof and warm',
      'Quilted cotton lining',
      'High-brightness reflective strips',
      'Spring yarn fabric',
      'Environmental PVC coating',
    ],
    specifications: {
      '型号': '1-6',
      '品名': '矿井防水棉衣',
      '面料': '210T春亚纺',
      '涂层': '环保PVC',
      '内里': '涤纶行缝棉',
      '静水压': '≥50 kPa',
      '反光带亮度': '≥500 (欧标)',
      '尺码': 'S/M/L/XL/XXL',
    },
    specificationsEn: {
      'Model': '1-6',
      'Product Name': 'Mine Waterproof Cotton Coat',
      'Fabric': '210T Spring Yarn',
      'Coating': 'Environmental PVC',
      'Lining': 'Polyester Quilted Cotton',
      'Hydrostatic Pressure': '≥50 kPa',
      'Reflective Strip Brightness': '≥500 (EN Standard)',
      'Size': 'S/M/L/XL/XXL',
    },
    applications: ['矿井作业', '隧道施工', '户外低温作业', '寒冷环境'],
    applicationsEn: ['Mining operations', 'Tunnel construction', 'Outdoor cold work', 'Cold environments'],
    applicationsAr: ['عمليات التعدين', 'بناء الأنفاق', 'العمل البارد في الهواء الطلق', 'البيئات الباردة'],
    applicationsDe: ['Bergbaubetriebe', 'Tunnelbau', 'Außenarbeit bei Kälte', 'Kalte Umgebungen'],
    applicationsEs: ['Operaciones mineras', 'Construcción de túneles', 'Trabajo frío al aire libre', 'Ambientes fríos'],
    color: '多色可选',
    material: '春亚纺+PVC涂层+涤纶棉',
  },
  {
    id: '1-32',
    slug: 'single-coated-long-raincoat',
    name: '单胶长雨衣',
    nameEn: 'Single-Coated Long Raincoat',
    nameAr: 'معطر مطري طويل أحادي الطلاء',
    nameDe: 'Einfach beschichteter langer Regenmantel',
    nameEs: 'Impermeable largo de un solo recubrimiento',
    category: 'rainwear',
    categoryEn: 'Rainwear Series',
    images: {
      main: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F1-23%E6%AD%A3%E9%9D%A2.jpg&nonce=fd120e86-3fc7-457d-8a8e-fe5c6c61f2a5&project_id=7620626575964323874&sign=856e5353b380fd4d35095fd820b14aa960e7d52f1109385419e6d5abce53b826',
    },
    description: '单胶长雨衣，内料采用全棉32×6058，涂层为天然橡胶，静水压≥70kPa。长款设计提供更大面积的防雨保护，适合雨天户外作业。',
    descriptionEn: 'Single-coated long raincoat with cotton 32×6058 lining and natural rubber coating. Hydrostatic pressure ≥70kPa. Long design provides extensive rain protection. Suitable for outdoor work in rainy conditions.',
    descriptionAr: 'معطر مطري طويل أحادي الطلاء مع بطانة قطنية 32×6058 وطلاء مطاطي طبيعي. ضغط هيدروستاتيكي ≥70 كيلو باسكال. التصميم الطويل يوفر حماية واسعة من المطر. مناسب للعمل في الهواء الطلق في الظروف الممطرة.',
    descriptionDe: 'Einfach beschichteter langer Regenmantel mit Baumwollfutter 32×6058 und Naturkautschuk-Beschichtung. Hydrostatischer Druck ≥70 kPa. Langes Design bietet umfangreichen Regenschutz. Geeignet für Außenarbeit bei Regen.',
    descriptionEs: 'Impermeable largo de un solo recubrimiento con forro de algodón 32×6058 y recubrimiento de caucho natural. Presión hidrostática ≥70 kPa. Diseño largo proporciona extensa protección contra lluvia. Adecuado para trabajo al aire libre en condiciones lluviosas.',
    features: [
      '单胶涂层',
      '天然橡胶',
      '全棉内料',
      '长款设计',
      '高静水压',
    ],
    featuresEn: [
      'Single-coated design',
      'Natural rubber coating',
      'Cotton lining',
      'Long-length design',
      'High hydrostatic pressure',
    ],
    specifications: {
      '型号': '1-32',
      '品名': '单胶长雨衣',
      '内料': '全棉32×6058',
      '涂层': '天然橡胶',
      '静水压': '≥70 kPa',
      '尺码': 'S/M/L/XL/XXL',
    },
    specificationsEn: {
      'Model': '1-32',
      'Product Name': 'Single-Coated Long Raincoat',
      'Lining': 'Cotton 32×6058',
      'Coating': 'Natural Rubber',
      'Hydrostatic Pressure': '≥70 kPa',
      'Size': 'S/M/L/XL/XXL',
    },
    applications: ['日常出行', '户外作业', '雨天通勤', '渔业作业'],
    applicationsEn: ['Daily travel', 'Outdoor work', 'Rainy commuting', 'Fishing'],
    applicationsAr: ['التنقل اليومي', 'العمل في الهواء الطلق', 'التنقل في الأيام الممطرة', 'الصيد'],
    applicationsDe: ['Tägliches Reisen', 'Außenarbeit', 'Regenpendeln', 'Angeln'],
    applicationsEs: ['Viaje diario', 'Trabajo al aire libre', 'Desplazamiento con lluvia', 'Pesca'],
    color: '多色可选',
    material: '全棉+天然橡胶',
  },
  {
    id: '2-3',
    slug: 'double-coated-mine-work-suit',
    name: '双胶矿井工作服',
    nameEn: 'Double-Coated Mine Work Suit',
    nameAr: 'بدلة عمل للمناجم مزدوجة الطلاء',
    nameDe: 'Doppelt beschichteter Minenarbeitsanzug',
    nameEs: 'Traje de trabajo para minas de doble recubrimiento',
    category: 'rainwear',
    categoryEn: 'Rainwear Series',
    images: {
      main: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F2-3%E6%AD%A3%E9%9D%A2.jpg&nonce=a1d08cf2-11a3-4831-917b-f8a9b591f8d7&project_id=7620626575964323874&sign=f4f12d1afa441b0abab63bc55161c264eda67952091c0e41806bd41d98415af3',
      side: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F2-3%E4%BE%A7%E9%9D%A2.jpg&nonce=2500249e-bedb-4a3c-8ef9-1346aeec5711&project_id=7620626575964323874&sign=9b9e33c32ea00694233e4a897677d40fc49b4a1b836c102b6dacb9331012c406',
      additional: [
        'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F2-3a.jpeg&nonce=8f8e5b98-a23c-4094-93a0-79e39338f0cf&project_id=7620626575964323874&sign=bcd1ce0f236b74771a8d8836f268de6aedf033163b8e96078d22b7aecad7bac2',
        'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F2-3a1.jpeg&nonce=f725961f-8879-44c6-828a-e0c0fe44fbd4&project_id=7620626575964323874&sign=f2b122476ea59d0b4704a8273a7e71c550e1955cf2a4f8d9f7485f9d4137b43d',
      ],
    },
    description: '双胶矿井工作服，内料采用涤棉，涂层为双面天然橡胶，静水压≥70kPa。适合矿井、隧道等潮湿作业环境。',
    descriptionEn: 'Double-coated mine work suit with polyester-cotton lining and double-sided natural rubber coating. Hydrostatic pressure ≥70kPa. Suitable for mines, tunnels and other damp environments.',
    descriptionAr: 'بدلة عمل للمناجم مزدوجة الطلاء مع بطانة بوليستر-قطن وطلاء مطاطي طبيعي مزدوج الجوانب. ضغط هيدروستاتيكي ≥70 كيلو باسكال. مناسبة للمناجم والأنفاق وبيئات العمل الرطبة.',
    descriptionDe: 'Doppelt beschichteter Minenarbeitsanzug mit Polyester-Baumwoll-Futter und zweiseitiger Naturkautschuk-Beschichtung. Hydrostatischer Druck ≥70 kPa. Geeignet für Minen, Tunnel und andere feuchte Umgebungen.',
    descriptionEs: 'Traje de trabajo para minas de doble recubrimiento con forro de poliéster-algodón y recubrimiento de caucho natural de doble cara. Presión hidrostática ≥70 kPa. Adecuado para minas, túneles y otros entornos húmedos.',
    features: [
      '双面天然橡胶',
      '高静水压',
      '涤棉内料',
      '矿井专用',
      '防水耐磨',
    ],
    featuresEn: [
      'Double-sided natural rubber',
      'High hydrostatic pressure',
      'Polyester-cotton lining',
      'Designed for mines',
      'Waterproof and durable',
    ],
    specifications: {
      '型号': '2-3',
      '品名': '双胶矿井工作服',
      '内料': '涤棉',
      '涂层': '双面天然橡胶',
      '静水压': '≥70 kPa',
      '尺码': 'S/M/L/XL/XXL',
    },
    specificationsEn: {
      'Model': '2-3',
      'Product Name': 'Double-Coated Mine Work Suit',
      'Lining': 'Polyester-Cotton',
      'Coating': 'Double-sided Natural Rubber',
      'Hydrostatic Pressure': '≥70 kPa',
      'Size': 'S/M/L/XL/XXL',
    },
    applications: ['矿井作业', '隧道施工', '潮湿环境', '户外重型作业'],
    applicationsEn: ['Mining operations', 'Tunnel construction', 'Damp environments', 'Heavy outdoor work'],
    applicationsAr: ['عمليات التعدين', 'بناء الأنفاق', 'البيئات الرطبة', 'العمل الثقيل في الهواء الطلق'],
    applicationsDe: ['Bergbaubetriebe', 'Tunnelbau', 'Feuchte Umgebungen', 'Schwere Außenarbeit'],
    applicationsEs: ['Operaciones mineras', 'Construcción de túneles', 'Ambientes húmedos', 'Trabajo pesado al aire libre'],
    color: '多色可选',
    material: '涤棉+天然橡胶',
  },
  {
    id: '2-41',
    slug: 'single-coated-hooded-suit',
    name: '单胶连帽套装',
    nameEn: 'Single-Coated Hooded Suit',
    nameAr: 'بدلة بغطاء رأس أحادية الطلاء',
    nameDe: 'Einfach beschichteter Anzug mit Kapuze',
    nameEs: 'Traje con capucha de un solo recubrimiento',
    category: 'rainwear',
    categoryEn: 'Rainwear Series',
    images: {
      main: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F2-41%E6%AD%A3%E9%9D%A2.jpeg&nonce=d9e0cbad-0fa0-49ff-a8e4-d19ee09269be&project_id=7620626575964323874&sign=22abfe803375e52873758d8258f442ff514fca82f14d662244eb795a5d2c5ce2',
      side: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F2-41%E4%BE%A7%E9%9D%A2.jpeg&nonce=a2dca722-8b02-4e5b-83cb-0b5dd3c0b6a6&project_id=7620626575964323874&sign=be12b7d50a1dd24783f565563de586d2df4996b698cbd89330efe4d5ab823a3d',
    },
    description: '单胶连帽套装，面料采用全棉32×6058，涂层为天然橡胶，静水压≥70kPa。连帽设计提供更好的头部防护，适合雨天户外作业。',
    descriptionEn: 'Single-coated hooded suit with cotton 32×6058 fabric and natural rubber coating. Hydrostatic pressure ≥70kPa. Hooded design provides better head protection. Suitable for outdoor work in rainy conditions.',
    descriptionAr: 'بدلة بغطاء رأس أحادية الطلاء مع قماش قطني 32×6058 وطلاء مطاطي طبيعي. ضغط هيدروستاتيكي ≥70 كيلو باسكال. تصميم بغطاء رأس يوفر حماية أفضل للرأس. مناسب للعمل في الهواء الطلق في الظروف الممطرة.',
    descriptionDe: 'Einfach beschichteter Anzug mit Kapuze aus Baumwollstoff 32×6058 und Naturkautschuk-Beschichtung. Hydrostatischer Druck ≥70 kPa. Kapuzendesign bietet besseren Kopfschutz. Geeignet für Außenarbeit bei Regen.',
    descriptionEs: 'Traje con capucha de un solo recubrimiento con tela de algodón 32×6058 y recubrimiento de caucho natural. Presión hidrostática ≥70 kPa. Diseño con capucha proporciona mejor protección para la cabeza. Adecuado para trabajo al aire libre en condiciones lluviosas.',
    features: [
      '单胶涂层',
      '天然橡胶',
      '全棉面料',
      '连帽设计',
      '高静水压',
    ],
    featuresEn: [
      'Single-coated design',
      'Natural rubber coating',
      'Cotton fabric',
      'Hooded design',
      'High hydrostatic pressure',
    ],
    specifications: {
      '型号': '2-41',
      '品名': '单胶连帽套装',
      '面料': '全棉32×6058',
      '涂层': '天然橡胶',
      '静水压': '≥70 kPa',
      '尺码': 'S/M/L/XL/XXL',
    },
    specificationsEn: {
      'Model': '2-41',
      'Product Name': 'Single-Coated Hooded Suit',
      'Fabric': 'Cotton 32×6058',
      'Coating': 'Natural Rubber',
      'Hydrostatic Pressure': '≥70 kPa',
      'Size': 'S/M/L/XL/XXL',
    },
    applications: ['户外作业', '雨天出行', '农业作业', '设备维护'],
    applicationsEn: ['Outdoor work', 'Rainy day travel', 'Agricultural work', 'Equipment maintenance'],
    applicationsAr: ['العمل في الهواء الطلق', 'السفر في الأيام الممطرة', 'العمل الزراعي', 'صيانة المعدات'],
    applicationsDe: ['Außenarbeit', 'Reisen bei Regen', 'Landwirtschaft', 'Gerätewartung'],
    applicationsEs: ['Trabajo al aire libre', 'Viaje en día lluvioso', 'Trabajo agrícola', 'Mantenimiento de equipos'],
    color: '多色可选',
    material: '全棉+天然橡胶',
  },
  {
    id: '1601',
    slug: 'polyester-suit-set',
    name: '涤丝纺套装',
    nameEn: 'Polyester Taffeta Suit',
    nameAr: 'بدلة تافيتا بوليستر',
    nameDe: 'Polyester-Taffeta-Anzug',
    nameEs: 'Traje de tafetán de poliéster',
    category: 'rainwear',
    categoryEn: 'Rainwear Series',
    images: {
      main: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F1610%E6%AD%A3%E9%9D%A2.jpg&nonce=7f4b3dda-b39a-49e9-b13a-a97cf96aa4b2&project_id=7620626575964323874&sign=5978eb28bab33fa9c6560da8f7ce1d1fcabd058cb0e14afcee6115333cbfce60',
      side: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F1610%E4%BE%A7%E9%9D%A2.jpg&nonce=a78c0521-f82c-48d0-969a-c29e071d403c&project_id=7620626575964323874&sign=ea7d90a9d53b3fa233c94849947abae8f43a127c7bbca0a16a2b4a2437f4d9f7',
    },
    description: '涤丝纺套装，面料采用190T涤纶表面泼水处理，涂层为PVC，内里为190T涤纶，静水压≥50kPa，织带反光带亮度≥300。适合户外作业和雨天出行。',
    descriptionEn: 'Polyester taffeta suit with 190T polyester fabric with water-repellent treatment, PVC coating, and 190T polyester lining. Hydrostatic pressure ≥50kPa, reflective tape brightness ≥300. Suitable for outdoor work and rainy day travel.',
    descriptionAr: 'بدلة تافيتا بوليستر مع قماش بوليستر 190T مع معالجة طاردة للماء، طلاء PVC، وبطانة بوليستر 190T. ضغط هيدروستاتيكي ≥50 كيلو باسكال، سطوع الشريط العاكس ≥300. مناسبة للعمل في الهواء الطلق والسفر في الأيام الممطرة.',
    descriptionDe: 'Polyester-Taffeta-Anzug aus 190T Polyester-Gewebe mit wasserabweisender Behandlung, PVC-Beschichtung und 190T Polyester-Futter. Hydrostatischer Druck ≥50 kPa, Reflektorband-Helligkeit ≥300. Geeignet für Außenarbeit und Regenwetter-Reisen.',
    descriptionEs: 'Traje de tafetán de poliéster con tela de poliéster 190T con tratamiento repelente al agua, recubrimiento de PVC y forro de poliéster 190T. Presión hidrostática ≥50 kPa, brillo de cinta reflectante ≥300. Adecuado para trabajo al aire libre y viaje en días lluviosos.',
    features: [
      '涤丝纺面料',
      '泼水处理',
      'PVC涂层',
      '反光织带',
      '轻便舒适',
    ],
    featuresEn: [
      'Polyester taffeta fabric',
      'Water-repellent treatment',
      'PVC coating',
      'Reflective tape',
      'Lightweight and comfortable',
    ],
    specifications: {
      '型号': '1601',
      '品名': '涤丝纺套装',
      '面料': '190T涤纶表面泼水处理',
      '涂层': 'PVC',
      '内里': '190T涤纶',
      '静水压': '≥50 kPa',
      '织带反光带亮度': '≥300',
      '尺码': 'S/M/L/XL/XXL',
    },
    specificationsEn: {
      'Model': '1601',
      'Product Name': 'Polyester Taffeta Suit',
      'Fabric': '190T Polyester Water-Repellent',
      'Coating': 'PVC',
      'Lining': '190T Polyester',
      'Hydrostatic Pressure': '≥50 kPa',
      'Reflective Tape Brightness': '≥300',
      'Size': 'S/M/L/XL/XXL',
    },
    applications: ['户外作业', '雨天出行', '路政作业', '物流运输'],
    applicationsEn: ['Outdoor work', 'Rainy day travel', 'Road maintenance', 'Logistics'],
    applicationsAr: ['العمل في الهواء الطلق', 'السفر في الأيام الممطرة', 'صيانة الطرق', 'الخدمات اللوجستية'],
    applicationsDe: ['Außenarbeit', 'Reisen bei Regen', 'Straßenwartung', 'Logistik'],
    applicationsEs: ['Trabajo al aire libre', 'Viaje en día lluvioso', 'Mantenimiento vial', 'Logística'],
    color: '多色可选',
    material: '涤丝纺+PVC涂层',
  },
  {
    id: '2-3a',
    slug: 'two-piece-reflective-rain-suit-blue',
    name: '分体式反光雨衣套装（蓝色款）',
    nameEn: 'Two-Piece Reflective Rain Suit (Blue)',
    nameAr: 'بدلة مطر زرقاء بقطعتين مع شرائط عاكسة',
    nameDe: 'Blauer zweiteiliger Regenanzug mit Reflektorstreifen',
    nameEs: 'Traje de lluvia azul de dos piezas con tiras reflectantes',
    category: 'rainwear',
    categoryEn: 'Rainwear Series',
    images: {
      main: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F2-3a%E6%AD%A3%E9%9D%A2.jpeg&nonce=f4874ea1-707d-40dc-a07f-cbe912eaf506&project_id=7620626575964323874&sign=4ff0ff3b12590af3140cae85e79e19718004b2e084332c80d504da2535d741cf',
      side: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F2-3a%E4%BE%A7%E9%9D%A2.jpeg&nonce=8e1dba1b-4bfe-4337-bd3f-7c729ae51a13&project_id=7620626575964323874&sign=13ce3caa1402e6764de45803038133e349df0ea91c31adfb3bc97060d5bd1ff8',
    },
    description: '蓝色分体式雨衣套装，上衣带有反光条设计，提升阴雨低能见度环境下的安全性。适合户外工作者和雨天出行使用。',
    descriptionEn: 'Blue two-piece rain suit with reflective strip design. Enhances safety in low-visibility rainy conditions. Suitable for outdoor workers and rainy day travel.',
    descriptionAr: 'بدلة مطر زرقاء بقطعتين مع تصميم شرائط عاكسة. تعزز السلامة في الظروف الممطرة ذات الرؤية المنخفضة. مناسبة للعاملين في الهواء الطلق والسفر في الأيام الممطرة.',
    descriptionDe: 'Blauer zweiteiliger Regenanzug mit Reflektorstreifen-Design. Erhöht die Sicherheit bei Regen mit geringer Sicht. Geeignet für Außenarbeiter und Regenwetter-Reisen.',
    descriptionEs: 'Traje de lluvia azul de dos piezas con diseño de tiras reflectantes. Mejora la seguridad en condiciones lluviosas de baja visibilidad. Adecuado para trabajadores al aire libre y viaje en días lluviosos.',
    features: [
      '蓝色款式',
      '反光条设计',
      '分体式套装',
      '防水材质',
      '舒适耐用',
    ],
    featuresEn: [
      'Blue color style',
      'Reflective strip design',
      'Two-piece set',
      'Waterproof material',
      'Comfortable and durable',
    ],
    specifications: {
      '材质': 'PVC防水面料',
      '颜色': '蓝色',
      '尺码': 'S/M/L/XL/XXL',
      '套装': '上衣+长裤',
    },
    specificationsEn: {
      'Material': 'PVC Waterproof Fabric',
      'Color': 'Blue',
      'Size': 'S/M/L/XL/XXL',
      'Set': 'Jacket + Pants',
    },
    applications: ['户外作业', '雨天出行', '路政作业', '物流运输'],
    applicationsEn: ['Outdoor work', 'Rainy day travel', 'Road maintenance', 'Logistics'],
    applicationsAr: ['العمل في الهواء الطلق', 'السفر في الأيام الممطرة', 'صيانة الطرق', 'الخدمات اللوجستية'],
    applicationsDe: ['Außenarbeit', 'Reisen bei Regen', 'Straßenwartung', 'Logistik'],
    applicationsEs: ['Trabajo al aire libre', 'Viaje en día lluvioso', 'Mantenimiento vial', 'Logística'],
    color: '蓝色',
    material: 'PVC防水面料',
  },
  {
    id: '4-2',
    slug: 'two-piece-hooded-rain-suit',
    name: '分体式连帽雨衣套装',
    nameEn: 'Two-Piece Hooded Rain Suit',
    nameAr: 'بدلة مطر بغطاء رأس بقطعتين',
    nameDe: 'Zweiteiliger Regenanzug mit Kapuze',
    nameEs: 'Traje de lluvia con capucha de dos piezas',
    category: 'rainwear',
    categoryEn: 'Rainwear Series',
    images: {
      main: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F4-2%E6%AD%A3%E9%9D%A2.jpg&nonce=0a00fed8-e187-435a-9339-a2c095cda88e&project_id=7620626575964323874&sign=cc7c16172bb0bab3070d43e22da07a30f9bfc79663fac6ee1d14001731289a35',
      side: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F4-2%E4%BE%A7%E9%9D%A2.jpg&nonce=8b501e8f-acc7-498d-a6a1-17488a61ff58&project_id=7620626575964323874&sign=df06be30f1a3ad7e54499dcd7972937bcd76617d4d7ca02c54eed80deb72982a',
    },
    description: '分体式连帽雨衣套装，采用优质防水面料制作，上衣带有连帽设计，提供全面的防雨保护。适合户外作业和日常雨天出行。',
    descriptionEn: 'Two-piece hooded rain suit made of high-quality waterproof material. Jacket features hooded design for full rain protection. Suitable for outdoor work and daily rainy day travel.',
    descriptionAr: 'بدلة مطر بغطاء رأس بقطعتين مصنوعة من مواد مقاومة للماء عالية الجودة. السترة بتصميم بغطاء رأس للحماية الكاملة من المطر. مناسبة للعمل في الهواء الطلق والسفر اليومي في الأيام الممطرة.',
    descriptionDe: 'Zweiteiliger Regenanzug mit Kapuze aus hochwertigem wasserdichtem Material. Jacke mit Kapuzendesign für vollständigen Regenschutz. Geeignet für Außenarbeit und tägliches Reisen bei Regen.',
    descriptionEs: 'Traje de lluvia con capucha de dos piezas hecho de material impermeable de alta calidad. La chaqueta cuenta con diseño con capucha para protección completa contra lluvia. Adecuado para trabajo al aire libre y viaje diario en días lluviosos.',
    features: [
      '连帽设计',
      '分体式套装',
      '防水面料',
      '舒适透气',
      '易于穿脱',
    ],
    featuresEn: [
      'Hooded design',
      'Two-piece set',
      'Waterproof material',
      'Comfortable and breathable',
      'Easy to wear and remove',
    ],
    specifications: {
      '材质': 'PVC防水面料',
      '颜色': '多色可选',
      '尺码': 'S/M/L/XL/XXL',
      '套装': '上衣+长裤',
    },
    specificationsEn: {
      'Material': 'PVC Waterproof Fabric',
      'Color': 'Various Colors',
      'Size': 'S/M/L/XL/XXL',
      'Set': 'Jacket + Pants',
    },
    applications: ['户外作业', '雨天出行', '物流运输', '农业作业'],
    applicationsEn: ['Outdoor work', 'Rainy day travel', 'Logistics', 'Agricultural work'],
    applicationsAr: ['العمل في الهواء الطلق', 'السفر في الأيام الممطرة', 'الخدمات اللوجستية', 'العمل الزراعي'],
    applicationsDe: ['Außenarbeit', 'Reisen bei Regen', 'Logistik', 'Landwirtschaft'],
    applicationsEs: ['Trabajo al aire libre', 'Viaje en día lluvioso', 'Logística', 'Trabajo agrícola'],
    color: '多色可选',
    material: 'PVC防水面料',
  },
  {
    id: '4-18',
    slug: 'two-piece-hooded-rain-suit-4-18',
    name: '分体式连帽雨衣套装',
    nameEn: 'Two-Piece Hooded Rain Suit',
    nameAr: 'بدلة مطر بغطاء رأس بقطعتين',
    nameDe: 'Zweiteiliger Regenanzug mit Kapuze',
    nameEs: 'Traje de lluvia con capucha de dos piezas',
    category: 'rainwear',
    categoryEn: 'Rainwear Series',
    images: {
      main: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F4-18%E6%AD%A3%E9%9D%A2.jpeg&nonce=e9def705-aa71-4fa7-942a-7c8f663197a9&project_id=7620626575964323874&sign=2f28b80fa3bdfec41451e3998fde9d4c439b8a1428a7ed7dcbc678a1a6d33ff2',
      side: 'https://code.coze.cn/api/sandbox/coze_coding/file/proxy?expire_time=-1&file_path=assets%2F4-18%E4%BE%A7%E9%9D%A2.jpeg&nonce=7f3a9c04-5914-4252-84de-ec4c7fb5092a&project_id=7620626575964323874&sign=3b0238f1df3e5a8bc7e13db3643401c3bc5416212acd25a6c9b82f2a197a3520',
    },
    description: '分体式连帽雨衣套装，设计简约大方，防水性能优异。上衣配有连帽，长裤为束脚款式，适合各类户外雨天作业场景。',
    descriptionEn: 'Two-piece hooded rain suit with simple and elegant design. Excellent waterproof performance. Jacket with hood, pants with cuffed style. Suitable for various outdoor rainy work scenarios.',
    descriptionAr: 'بدلة مطر بغطاء رأس بقطعتين بتصميم بسيط وأنيق. أداء ممتاز في مقاومة الماء. سترة بغطاء رأس، بنطلون بتصميم مزمك عند الكاحل. مناسبة لسيناريوهات العمل المختلفة في الهواء الطلق في الأيام الممطرة.',
    descriptionDe: 'Zweiteiliger Regenanzug mit Kapuze in schlichtem und elegantem Design. Ausgezeichnete Wasserdichtigkeit. Jacke mit Kapuze, Hose mit Bündchen. Geeignet für verschiedene Außenarbeiten bei Regen.',
    descriptionEs: 'Traje de lluvia con capucha de dos piezas con diseño simple y elegante. Excelente rendimiento impermeable. Chaqueta con capucha, pantalones con estilo acintado. Adecuado para varios escenarios de trabajo lluvioso al aire libre.',
    features: [
      '连帽设计',
      '简约大方',
      '防水优异',
      '束脚长裤',
      '舒适耐用',
    ],
    featuresEn: [
      'Hooded design',
      'Simple and elegant',
      'Excellent waterproof',
      'Cuffed pants',
      'Comfortable and durable',
    ],
    specifications: {
      '材质': 'PVC防水面料',
      '颜色': '多色可选',
      '尺码': 'S/M/L/XL/XXL',
      '套装': '上衣+长裤',
    },
    specificationsEn: {
      'Material': 'PVC Waterproof Fabric',
      'Color': 'Various Colors',
      'Size': 'S/M/L/XL/XXL',
      'Set': 'Jacket + Pants',
    },
    applications: ['户外作业', '雨天出行', '设备维护', '农业作业'],
    applicationsEn: ['Outdoor work', 'Rainy day travel', 'Equipment maintenance', 'Agricultural work'],
    applicationsAr: ['العمل في الهواء الطلق', 'السفر في الأيام الممطرة', 'صيانة المعدات', 'العمل الزراعي'],
    applicationsDe: ['Außenarbeit', 'Reisen bei Regen', 'Gerätewartung', 'Landwirtschaft'],
    applicationsEs: ['Trabajo al aire libre', 'Viaje en día lluvioso', 'Mantenimiento de equipos', 'Trabajo agrícola'],
    color: '多色可选',
    material: 'PVC防水面料',
  },
];

export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter(p => p.category === categoryId);
}

export function getProductById(id: string): Product | undefined {
  return products.find(p => p.id === id);
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find(p => p.slug === slug);
}

// Get product URL (SEO-friendly)
export function getProductUrl(product: Product): string {
  return `/products/${product.slug}`;
}
